<a href="https://colab.research.google.com/github/Wikanda-Hongboonmee/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Function

การเขียน Function ในนี้

def function_name (_Input_) :

       do_something with _Input_ to produce _output_

       return _output_

Function มีส่วนประกอบสำคัญ 4 ส่วน คือ

          1. บอก Python ว่าเราจะเขียนฟังก์ชันชื่ออะไร (ขาดไม่ได้)

          2. กำหนดตัวแปรที่จะเป็น input (ขาดได้)

          3. ส่วนประมวลผล do_something with Input to get Output (ขาดไม่ได้)

          4. ส่วน output return (ขาดได้)

In [ ]:
def print_name (name,surname,ID) :  #เราจะใช้เว้นวรรคในการบอกขอบเขตของ code
    st = f"ชื่อ {name} นามสกุล {surname} ID {ID}"
    return st

การเรียกใช้ฟังก์ชัน


In [ ]:
print_name ("วิกานดา" , "หงษ์บุญมี" ,"623020764-2")

'ชื่อ วิกานดา นามสกุล หงษ์บุญมี ID 623020764-2'

In [ ]:
output_string = print_name ("วิกานดา" , "หงษ์บุญมี" ,"623020764-2")
print (output_string)

ชื่อ วิกานดา นามสกุล หงษ์บุญมี ID 623020764-2


In [ ]:
#ฟังก์ชันไม่จำเป็นต้องมี output

In [ ]:
def print_name2 (surname,ID,name) :  #เราจะใช้เว้นวรรคในการบอกขอบเขตของ code
    st = f"ชื่อ {name} นามสกุล {surname} รหัส {ID}"
    print(st)

In [ ]:
op2 = print_name2 ("วิกานดา" , "หงษ์บุญมี" ,"623020764-2")

ชื่อ 623020764-2 นามสกุล วิกานดา รหัส หงษ์บุญมี


In [ ]:
print (op2)

None


ฟังก์ชันไม่จำเป็นต้องมี input

In [ ]:
def Pi() :
    return 3.14159265359

In [ ]:
#คำนวณพื้นที่วงกลมที่เส้นผ่านศูนย์กลางเท่ากับ 3
Pi() * (1.5**2) # ** คือยกกำลังสอง

7.0685834705775

In [ ]:
def print_my_name () :
      print ("วิกานดา หงษ์บุญมี ID 623020764-2")

In [ ]:
print_my_name ()

วิกานดา หงษ์บุญมี ID 623020764-2


input ของฟังก์ชันใน python มี2แบบ  input ที่จำเป็นต้องใส่ กับ input ที่ไม่จำเป็นต้องใส่ (มีค่า default) จะต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน


In [ ]:
def print_2lines_default (name, surname, ID , grade ="F") :
      st = f' ชื่อ {name} นามสกุล {surname} รหัส {ID} '
      print (st)
      st2 = f'เกรดวิชา Multivariate >>> {grade}'
      print (st2)

In [ ]:
print_2lines_default ("วิกานดา","หงษ์บุญมี","623020764-2")

 ชื่อ วิกานดา นามสกุล หงษ์บุญมี รหัส 623020764-2 
เกรดวิชา Multivariate >>> F


In [ ]:
print_2lines_default ("วิกานดา","หงษ์บุญมี","623020764-2","A")

 ชื่อ วิกานดา นามสกุล หงษ์บุญมี รหัส 623020764-2 
เกรดวิชา Multivariate >>> A


เราสามารถเรียกฟังก์ชันโดยใช้ชื่อตัวแปรของฟังก์ชันช่วยได้ 

In [ ]:
print_name2 (name = "วิกานดา" , surname = "หงษ์บุญมี" , ID = "623020764-2")

ชื่อ วิกานดา นามสกุล หงษ์บุญมี รหัส 623020764-2


# HW 3  ให้เขียน Function คำนวณจำนวนวินาทีจาก เวลา ต่อไปนี้
 
 
'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [ ]:
def times (times) :
      times_sp = times.split('-')
      total = int(times_sp[0])*3600 + int(times_sp[1])*60 + int(times_sp[2])
      st = f' เวลา {times} น. สามารถคำนวณเป็นวินาทีได้เท่ากับ {total} วินาที'
      print (st)

In [ ]:
times ('14-15-31')

 เวลา 14-15-31 น. สามารถคำนวณเป็นวินาทีได้เท่ากับ 51331 วินาที


In [ ]:
times ('13-00-01')

 เวลา 13-00-01 น. สามารถคำนวณเป็นวินาทีได้เท่ากับ 46801 วินาที


In [ ]:
times ('05-49-44')

 เวลา 05-49-44 น. สามารถคำนวณเป็นวินาทีได้เท่ากับ 20984 วินาที


In [ ]:
times ('00-00-16')

 เวลา 00-00-16 น. สามารถคำนวณเป็นวินาทีได้เท่ากับ 16 วินาที


Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

ย่อมาจาก Number - Numerical + py - python 

ขั้นตอนการใช้งาน package

1.``` import``` ```ชื่อ package ``` #เรียกใช้ package

2.```ชื่อ package```.```ชื่อฟังก์ชัน```# เรียกใช้ function 


In [1]:
import numpy


data structure -> array

สร้าง array (nampy array) 

In [2]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print (mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


การชี้ค่าใน numpy array

In [6]:
mat_ex1[1,1] # [แถว,หลัก] ด้านหน้าแถว ด้านหลังหลัก นับตามหลัก python เริ่มจาก 0

0.1

ถ้าไม่มี numpy array 

In [7]:
list_ex1 = ([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print (list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [14]:
list_ex1 [1][1] 

0.1

In [19]:
print (list_ex1)
a = list_ex1[1]
print (a)
print (a[1]) #ชี้สมาชิกตัวที่เท่าไหร่ของlist

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operations

data 2 แบบ -> matrix ( array 2 มิติ ) , scalar ( ตัวเลขที่เป็นค่าคงที่ )

In [20]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print (mat_ex1)
mat_ex2 = numpy.array([[2.0,3.7,5.9],[91,1.5,7.3]])
print (mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกกันหรือลบกัน

หน้าตาของ matrix ต้องเหมือนกัน

In [21]:
mat_ex3 = mat_ex1 + mat_ex2 
print (mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print (mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


การตรวจสอบขนาดของ matrix 

In [22]:
mat_ex3.shape

(2, 3)

In [24]:
mat_ex3.shape[1] #ชี้ตำแหน่งของสมาชิกเหมือนกับ list

3

In [26]:
print (mat_ex1)
print (mat_ex2) 

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


In [25]:
mat_ex1 * mat_ex2  # การคูณเมทริกซ์ไม่ได้ใช้เครื่องหมาย *

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

In [29]:
numpy.dot(mat_ex1,mat_ex2) #เมทริกซ์ขนาด (2,3) กับเมทริกซ์ขนาด (2,3) คูณกันไม่ได้ ตามหลักของเมทริกซ์

ValueError: ignored

#การคูณเมทริกซ์ (แถวคูณหลัก)

(หลักของตัวข้างหน้าต้องเท่ากับแถวของตัวข้างหลัง)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

``` matrix.T```

In [41]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2) จะได้เป็นเมทริกซ์ขนาด (2,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [44]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) จะได้เป็นเมทริกซ์ขนาด (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

# HW 4

อธิบายการหา Determinant และ Inverse matrix (รูปและคำอธิบาย)
